name: Build

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  plugin_test:
    name: asdf plugin test
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: asdf_plugin_test
        uses: asdf-vm/actions/plugin-test@v2
        with:
          command: signal-cli --version
